### ISSUE TITLE
Embeds don't all seem to be working

### ISSUE THREAD

**Issue by florango** [adobe/helix-embed#145] opened 2020-02-18 03:29 UTC
Check out this page:

https://helix-pipeline-adobe.project-helix.page/test/fixtures/embeds.html

The file embeds are working, but things like YouTube don't work.

**Comment by trieloff** [comment] 2020-02-19 00:14
> It looks like this is an issue with the `helix-embed` service's configuration.

… but it isn't. It's a duplicate of https://github.com/adobe/helix-pipeline/issues/559, i.e. a missing `/` in the embed concatenation

**Closed by trieloff** 2020-02-19 00:14 UTC
